# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=10)),
                ('test2', models.TextField()),
                ('test3', models.IntegerField(default=0)),
            ],
        ),
    ]
